name: .NET

on:
  push:
    branches: ["master"]
    tags: ["v*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

env:
  DOTNET_VERSION: 8.0.x
  TEST_PROJECT_PATH: Test/qon.Tests.csproj
  SPATIAL_PROJECT_PATH: qon.Spatial/qon.Spatial.csproj
  PACKAGE_OUTPUT_ROOT: ./artifacts/nuget
  CONFIGURATION: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore qon.sln

      - name: Build
        run: dotnet build qon.sln --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Test
        run: dotnet test ${{ env.TEST_PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-build --verbosity normal

  publish:
    needs: build
    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore qon.sln

      - name: Pack qon and qon.Spatial
        run: dotnet pack ${{ env.SPATIAL_PROJECT_PATH }} --configuration ${{ env.CONFIGURATION }} --no-restore --output ${{ env.PACKAGE_OUTPUT_ROOT }}

      - name: Publish qon to NuGet.org
        run: dotnet nuget push "${{ env.PACKAGE_OUTPUT_ROOT }}/qon.[0-9]*.nupkg" --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET }}" --skip-duplicate

      - name: Publish qon.Spatial to NuGet.org
        run: dotnet nuget push "${{ env.PACKAGE_OUTPUT_ROOT }}/qon.Spatial.[0-9]*.nupkg" --source https://api.nuget.org/v3/index.json --api-key "${{ secrets.NUGET }}" --skip-duplicate
